### ISSUE TITLE
SDK path incorrect, app doesn't build

### ISSUE THREAD

**Issue by truh** [svanderburg/nix-androidenvtests#2]
## Issue description

First of all, I'm not certain if this issue is limited to `svanderburg/nix-androidenvtests` or affects the `androidenv` package in general. I'm sorry if I reported this to the wrong location.

From what I can tell either `nix-androidenvtests` or the `androidenv` package in nixpkgs is looking for the android sdk in the wrong location.

### Steps to reproduce

```
git clone git@github.com:svanderburg/nix-androidenvtests.git
cd nix-androidenvtests/deployment
nix-build -A emulate_myfirstapp_debug.host_x86_64-linux.build_16.emulate_16.armeabi-v7a
```

Fails with the error message

```
BUILD FAILED
/tmp/nix-build-MyFirstApp-debug.drv-0/myfirstapp/build.xml:93: Cannot find /nix/store/d724xph16zxfsl2s60a8f3dk9yxjsn4h-android-sdk-25.1.7/libexec/android-sdk-linux/tools/ant/build.xml imported from /tmp/nix-build-MyFirstApp-debug.drv-0/myfirstapp/build.xml
```

I got around this first failure by adding this line to the ant config `nix-androidenvtests/src/ant.properties`:

    sdk.dir = /nix/store/d724xph16zxfsl2s60a8f3dk9yxjsn4h-android-sdk-25.1.7/libexec/

After setting the sdk directory in the ant config file `nix-build` completes without errors.

I get similar errors when I now try to run `result/bin/run-test-emulator` which crashes with the following error message:

```
Looking for a free TCP port in range 5554-5584
result/bin/run-test-emulator: line 19: /nix/store/3i59p627w74scwpq6gr31v7185npw9a3-android-sdk-25.1.7/libexec/android-sdk-*/platform-tools/adb: No such file or directory
We have a free TCP port: 5554
result/bin/run-test-emulator: line 38: /nix/store/3i59p627w74scwpq6gr31v7185npw9a3-android-sdk-25.1.7/libexec/android-sdk-*/tools/android: No such file or directory
result/bin/run-test-emulator: line 41: /nix/store/3i59p627w74scwpq6gr31v7185npw9a3-android-sdk-25.1.7/libexec/android-sdk-*/tools/android: No such file or directory
```

I can get rid of these error messages by removing `android-sdk-*/` from all the paths like this:

```
sed -e "s|android\-sdk\-\*/||" result/bin/run-test-emulator > /tmp/jakob_run-test-emulator
bash /tmp/jakob_run-test-emulator
```

From the console output it now looks like it executes just fine but no emulator window appears.

```
Looking for a free TCP port in range 5554-5584
We have a free TCP port: 5554
Auto-selecting single ABI armeabi-v7a
Android 4.1.2 is a basic Android platform.
Do you wish to create a custom hardware profile [no]Created AVD 'device' based on Android 4.1.2, ARM (armeabi-v7a) processor,
with the following hardware config:
hw.lcd.density=240
hw.ramSize=512
vm.heapSize=48
Waiting until the emulator has booted the device and the package manager is ready...
emulator: WARNING: Classic qemu does not support SMP. The hw.cpu.ncore option from your config file is ignored.
```

## Technical details

* System:`16.09pre87999.20f009d (Flounder)`
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: `16.09pre87999.20f009d`

**Comment by svanderburg** [comment]
Hi,

The Android infrastructure was indeed broken in Nixpkgs and I fixed it a while ago. Can you check if you are using the latest revisions of the Nixpkgs master or 16.09 branches (or be sure that the you have the latest expressions from the channel by running: `nix-channel --update`)?

I just ran the tests locally and for me they seem to work just fine.

**Comment by truh** [comment]
Hallo,

I thought I was already on the newest version but for some reason I wasn't. After updating the user channel as well as the root channel, both building the app and starting the emulator works fine.

Thanks a lot for your help.
