### ISSUE TITLE
Build succeeds, but the emulator fails to start (missing runtime deps?)

### ISSUE THREAD

**Issue by jpotier** [svanderburg/nix-androidenvtests#3]
(I'm running nix-build on ArchLinux)

Apparently, there are still some missing runtime dependencies:

    libGL error: unable to load driver: swrast_dri.so
    libGL error: failed to load driver: swrast

Here's the full log:

    deployment [master●] ./result/bin/run-test-emulator
    Looking for a free TCP port in range 5554-5584
    We have a free TCP port: 5554
    Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
    Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
    Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
    Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
    Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
    Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
    Auto-selecting single ABI armeabi-v7a
    Android 4.1.2 is a basic Android platform.
    Do you wish to create a custom hardware profile [no]Created AVD 'device' based on Android 4.1.2, ARM (armeabi-v7a) processor,
    with the following hardware config:
    hw.lcd.density=240
    hw.ramSize=512
    vm.heapSize=48
    Waiting until the emulator has booted the device and the package manager is ready...
    libGL error: unable to load driver: swrast_dri.so
    libGL error: failed to load driver: swrast
    X Error of failed request:  GLXBadContext
      Major opcode of failed request:  154 (GLX)
      Minor opcode of failed request:  6 (X_GLXIsDirect)
      Serial number of failed request:  48
      Current serial number in output stream:  47
    libGL error: unable to load driver: swrast_dri.so
    libGL error: failed to load driver: swrast
    X Error of failed request:  GLXBadContext
      Major opcode of failed request:  154 (GLX)
      Minor opcode of failed request:  6 (X_GLXIsDirect)
      Serial number of failed request:  48
      Current serial number in output stream:  47
    emulator: WARNING: Classic qemu does not support SMP. The hw.cpu.ncore option from your config file is ignored.
    libGL error: unable to load driver: swrast_dri.so
    libGL error: failed to load driver: swrast
    X Error of failed request:  BadValue (integer parameter out of range for operation)
      Major opcode of failed request:  154 (GLX)
      Minor opcode of failed request:  24 (X_GLXCreateNewContext)
      Value in failed request:  0x0
      Serial number of failed request:  32
      Current serial number in output stream:  33
    QObject::~QObject: Timers cannot be stopped from another thread

**Comment by S-NA** [comment]
I seem to have run into this problem on NixOS, and non-NixOS distributions. Setting `enableGPU = false` fixed it for me.

**Comment by svanderburg** [comment]
I think this problem no longer exists in the current version. I'm closing this issue.
